version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fastapi_db

  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alembic_runner
    depends_on:
      - db
    command: alembic upgrade head
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fastapi_db
    volumes:
      - .:/code

volumes:
  postgres_data:
