version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
      - rabbitmq
      - redis
    env_file:
      - ./env/.env.${ENV:-local}
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: ["./wait-for-it.sh", "db:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-demo
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    depends_on:
      - api
      - rabbitmq
      - redis
    env_file:
      - ./env/.env.${ENV:-local}
    command: ["./wait-for-it.sh", "db:5432", "--", "celery", "-A", "app.tasks.celery_worker", "worker", "-Q", "emails", "--loglevel=info"]
    volumes:
      - .:/code
  
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"    # Web UI
      - "1025:1025"    # SMTP

volumes:
  postgres_data:
  rabbitmq_data: