version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
      - rabbitmq
    env_file:
      - ./env/.env.${ENV:-local}
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: ["./wait-for-it.sh", "db:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # for celery
      - "15672:15672" # for RabbitMQ management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    depends_on:
      - api
      - rabbitmq
    env_file:
      - ./env/.env.${ENV:-local}
    command: ["./wait-for-it.sh", "db:5432", "--", "celery", "-A", "app.tasks.celery_worker", "worker", "--loglevel=info"]
    volumes:
      - .:/code

volumes:
  postgres_data:
  rabbitmq_data:
